// bySpec is keyed by spec series shortname (matching production specs.json shape),
// mapping to all DataEntry items for that series. Each entry retains its versioned
// spec id in the `spec` field to allow version-preference tests.
//
// Entries carry `term`, as production specs.json does. Without it, two distinct
// definitions in one spec are indistinguishable by spec+type and get collapsed.
export default {
  "referrer-policy": [
    {
      term: "",
      type: "enum-value",
      spec: "referrer-policy-1",
      shortname: "referrer-policy",
      status: "current",
      uri: "#dom-referrerpolicy",
      for: ["ReferrerPolicy"],
    },
  ],
  "fetch": [
    {
      term: "",
      type: "enum-value",
      spec: "fetch",
      shortname: "fetch",
      status: "current",
      uri: "#dom-requestdestination",
      for: ["RequestDestination"],
    },
    {
      term: "script",
      type: "enum-value",
      spec: "fetch",
      shortname: "fetch",
      status: "current",
      uri: "#dom-requestdestination-script",
      for: ["RequestDestination"],
    },
    {
      term: "body",
      type: "dfn",
      spec: "fetch",
      shortname: "fetch",
      status: undefined,
      uri: "#concept-body",
    },
  ],
  "xhr": [
    {
      term: "",
      type: "enum-value",
      spec: "xhr",
      shortname: "xhr",
      status: "current",
      uri: "#dom-xmlhttprequestresponsetype",
      for: ["XMLHttpRequestResponseType"],
    },
  ],
  "font-metrics-api": [
    {
      term: "Baseline",
      type: "interface",
      spec: "font-metrics-api-1",
      shortname: "font-metrics-api",
      status: "current",
      uri: "#baseline",
      normative: true,
    },
  ],
  "svg": [
    {
      term: "baseline",
      type: "dfn",
      spec: "svg2",
      shortname: "svg",
      status: "snapshot",
      uri: "text.html#TermBaseline",
    },
    {
      term: "baseline",
      type: "dfn",
      spec: "svg2",
      shortname: "svg",
      status: "current",
      uri: "text.html#TermBaseline",
    },
    {
      term: "script",
      type: "element",
      spec: "svg2",
      shortname: "svg",
      status: "snapshot",
      uri: "interact.html#elementdef-script",
    },
    {
      term: "script",
      type: "element",
      spec: "svg2",
      shortname: "svg",
      status: "current",
      uri: "interact.html#elementdef-script",
    },
    {
      term: "marker",
      type: "element",
      spec: "svg2",
      shortname: "svg",
      status: "snapshot",
      uri: "painting.html#elementdef-marker",
    },
    {
      term: "marker",
      type: "element",
      spec: "svg2",
      shortname: "svg",
      status: "current",
      uri: "painting.html#elementdef-marker",
    },
    {
      term: "script",
      type: "element",
      spec: "svg",
      shortname: "svg",
      status: "snapshot",
      uri: "script.html#ScriptElement",
    },
    {
      term: "marker",
      type: "element",
      spec: "svg",
      shortname: "svg",
      status: "snapshot",
      uri: "painting.html#MarkerElement",
    },
  ],
  "html": [
    {
      term: "event handler",
      type: "dfn",
      spec: "html",
      shortname: "html",
      status: "snapshot",
      uri: "webappapis.html#event-handlers",
    },
    {
      term: "script",
      type: "element",
      spec: "html",
      shortname: "html",
      status: "snapshot",
      uri: "scripting.html#script",
    },
    {
      term: "script",
      type: "dfn",
      spec: "html",
      shortname: "html",
      status: "snapshot",
      uri: "webappapis.html#concept-script",
    },
    {
      term: "body",
      type: "element",
      spec: "html",
      shortname: "html",
      status: undefined,
      uri: "sections.html#the-body-element",
    },
    {
      term: "event",
      type: "attribute",
      spec: "html",
      shortname: "html",
      status: "snapshot",
      uri: "obsolete.html#dom-script-event",
      for: ["HTMLScriptElement"],
    },
  ],
  "css-cascade": [
    {
      term: "inherited value",
      type: "dfn",
      spec: "css-cascade-3",
      shortname: "css-cascade",
      status: "snapshot",
      uri: "#inherited-value",
    },
    {
      term: "inherited value",
      type: "dfn",
      spec: "css-cascade-3",
      shortname: "css-cascade",
      status: "current",
      uri: "#inherited-value",
    },
    {
      term: "inherited value",
      type: "dfn",
      spec: "css-cascade-4",
      shortname: "css-cascade",
      status: "snapshot",
      uri: "#inherited-value",
    },
    {
      term: "inherited value",
      type: "dfn",
      spec: "css-cascade-4",
      shortname: "css-cascade",
      status: "current",
      uri: "#inherited-value",
    },
  ],
  "css-lists": [
    {
      term: "marker",
      type: "dfn",
      spec: "css-lists-3",
      shortname: "css-lists",
      status: "current",
      uri: "#marker",
    },
  ],
  "dom": [
    {
      term: "EventInit",
      type: "dictionary",
      spec: "dom",
      shortname: "dom",
      status: "snapshot",
      uri: "#dictdef-eventinit",
    },
    {
      term: "event",
      type: "dfn",
      spec: "dom",
      shortname: "dom",
      status: "snapshot",
      uri: "#concept-event",
    },
    {
      term: "event",
      type: "attribute",
      spec: "dom",
      shortname: "dom",
      status: "snapshot",
      uri: "#dom-window-event",
      for: ["Window"],
    },
    {
      term: "aborted",
      type: "attribute",
      spec: "dom",
      shortname: "dom",
      status: "snapshot",
      uri: "#dom-abortsignal-aborted",
      for: ["AbortSignal"],
    },
  ],
  "web-bluetooth": [
    {
      term: "[[context]]",
      type: "attribute",
      spec: "web-bluetooth-1",
      shortname: "web-bluetooth",
      status: "snapshot",
      uri: "#dom-bluetoothdevice-context-slot",
      for: ["BluetoothDevice"],
    },
  ],
  "infra": [
    {
      term: "for each",
      type: "dfn",
      spec: "infra",
      shortname: "infra",
      status: "current",
      uri: "#list-iterate",
      for: ["list","set"],
    },
    {
      term: "user agent",
      type: "dfn",
      spec: "infra",
      shortname: "infra",
      status: "current",
      uri: "#user-agent",
      normative: true,
    },
  ],
  "wai-aria": [
    {
      term: "user agents",
      type: "dfn",
      spec: "wai-aria-1.2",
      shortname: "wai-aria",
      status: "current",
      uri: "#dfn-user-agent",
      normative: false,
    },
  ],
  cookiestore: [
    {
      term: "name",
      type: "dict-member",
      spec: "cookiestore",
      shortname: "cookiestore",
      status: "snapshot",
      uri: "https://www.w3.org/TR/cookiestore/#dom-cookieinit-name",
      for: ["CookieInit"],
    },
    {
      term: "name",
      type: "dict-member",
      spec: "cookiestore",
      shortname: "cookiestore",
      status: "snapshot",
      uri: "https://www.w3.org/TR/cookiestore/#dom-cookielistitem-name",
      for: ["CookieListItem"],
    },
  ],
};
