// bySpec is keyed by spec id (not shortname), mapping to all DataEntry items
// for that spec. This is derived from the data in data-by-term.js.
export default {
  "referrer-policy-1": [
    {
      type: "enum-value",
      spec: "referrer-policy-1",
      shortname: "referrer-policy",
      status: "current",
      uri: "#dom-referrerpolicy",
      for: ["ReferrerPolicy"],
    },
  ],
  fetch: [
    {
      type: "enum-value",
      spec: "fetch",
      shortname: "fetch",
      status: "current",
      uri: "#dom-requestdestination",
      for: ["RequestDestination"],
    },
    {
      type: "enum-value",
      spec: "fetch",
      shortname: "fetch",
      status: "current",
      uri: "#dom-requestdestination-script",
      for: ["RequestDestination"],
    },
    {
      shortname: "fetch",
      spec: "fetch",
      uri: "#concept-body",
      type: "dfn",
    },
  ],
  xhr: [
    {
      type: "enum-value",
      spec: "xhr",
      shortname: "xhr",
      status: "current",
      uri: "#dom-xmlhttprequestresponsetype",
      for: ["XMLHttpRequestResponseType"],
    },
  ],
  "font-metrics-api-1": [
    {
      type: "interface",
      spec: "font-metrics-api-1",
      shortname: "font-metrics-api",
      status: "current",
      uri: "#baseline",
      normative: true,
      htmlProse: "test html Prose",
    },
  ],
  svg2: [
    {
      type: "dfn",
      spec: "svg2",
      shortname: "svg",
      status: "snapshot",
      uri: "text.html#TermBaseline",
    },
    {
      type: "dfn",
      spec: "svg2",
      shortname: "svg",
      status: "current",
      uri: "text.html#TermBaseline",
    },
    {
      type: "element",
      spec: "svg2",
      shortname: "svg",
      status: "snapshot",
      uri: "interact.html#elementdef-script",
    },
    {
      type: "element",
      spec: "svg2",
      shortname: "svg",
      status: "current",
      uri: "interact.html#elementdef-script",
    },
    {
      type: "element",
      spec: "svg2",
      shortname: "svg",
      status: "snapshot",
      uri: "painting.html#elementdef-marker",
    },
    {
      type: "element",
      spec: "svg2",
      shortname: "svg",
      status: "current",
      uri: "painting.html#elementdef-marker",
    },
  ],
  html: [
    {
      type: "dfn",
      spec: "html",
      shortname: "html",
      status: "snapshot",
      uri: "webappapis.html#event-handlers",
    },
    {
      type: "element",
      spec: "html",
      shortname: "html",
      status: "snapshot",
      uri: "scripting.html#script",
    },
    {
      type: "dfn",
      spec: "html",
      shortname: "html",
      status: "snapshot",
      uri: "webappapis.html#concept-script",
    },
    {
      shortname: "html",
      spec: "html",
      uri: "sections.html#the-body-element",
      type: "element",
    },
    {
      type: "attribute",
      spec: "html",
      shortname: "html",
      status: "snapshot",
      uri: "obsolete.html#dom-script-event",
      for: ["HTMLScriptElement"],
    },
  ],
  svg: [
    {
      type: "element",
      spec: "svg",
      shortname: "svg",
      status: "snapshot",
      uri: "script.html#ScriptElement",
    },
    {
      type: "element",
      spec: "svg",
      shortname: "svg",
      status: "snapshot",
      uri: "painting.html#MarkerElement",
    },
  ],
  "css-cascade-3": [
    {
      type: "dfn",
      spec: "css-cascade-3",
      shortname: "css-cascade",
      status: "snapshot",
      uri: "#inherited-value",
    },
    {
      type: "dfn",
      spec: "css-cascade-3",
      shortname: "css-cascade",
      status: "current",
      uri: "#inherited-value",
    },
  ],
  "css-cascade-4": [
    {
      type: "dfn",
      spec: "css-cascade-4",
      shortname: "css-cascade",
      status: "snapshot",
      uri: "#inherited-value",
    },
    {
      type: "dfn",
      spec: "css-cascade-4",
      shortname: "css-cascade",
      status: "current",
      uri: "#inherited-value",
    },
  ],
  "css-lists-3": [
    {
      type: "dfn",
      spec: "css-lists-3",
      shortname: "css-lists",
      status: "current",
      uri: "#marker",
    },
  ],
  dom: [
    {
      type: "dictionary",
      spec: "dom",
      shortname: "dom",
      status: "snapshot",
      uri: "#dictdef-eventinit",
    },
    {
      type: "dfn",
      spec: "dom",
      shortname: "dom",
      status: "snapshot",
      uri: "#concept-event",
    },
    {
      type: "attribute",
      spec: "dom",
      shortname: "dom",
      status: "snapshot",
      uri: "#dom-window-event",
      for: ["Window"],
    },
    {
      type: "attribute",
      spec: "dom",
      shortname: "dom",
      status: "snapshot",
      uri: "#dom-abortsignal-aborted",
      for: ["AbortSignal"],
    },
  ],
  "web-bluetooth-1": [
    {
      type: "attribute",
      spec: "web-bluetooth-1",
      shortname: "web-bluetooth",
      status: "snapshot",
      uri: "#dom-bluetoothdevice-context-slot",
      for: ["BluetoothDevice"],
    },
  ],
  infra: [
    {
      type: "dfn",
      spec: "infra",
      shortname: "infra",
      status: "current",
      uri: "#list-iterate",
      for: ["list", "set"],
    },
    {
      type: "dfn",
      spec: "infra",
      shortname: "infra",
      status: "current",
      uri: "#user-agent",
      normative: true,
    },
  ],
  "wai-aria-1.2": [
    {
      type: "dfn",
      spec: "wai-aria-1.2",
      shortname: "wai-aria",
      status: "current",
      uri: "#dfn-user-agent",
      normative: false,
    },
  ],
};
