name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v7
        with:
          node-version-file: .nvmrc
          cache: pnpm
      - run: pnpm install

      - name: Lint, typecheck & test
        parallel:
          - name: Lint
            run: pnpm lint
          - name: Typecheck
            run: pnpm typecheck
          - name: Test
            run: pnpm test
